import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#5a00c6',
        'surface-container': '#eceef0',
        'inverse-on-surface': '#eff1f3',
        'secondary-fixed-dim': '#d2bbff',
        'on-error': '#ffffff',
        'on-secondary-fixed': '#25005a',
        'on-primary-container': '#eeefff',
        surface: '#f7f9fb',
        error: '#ba1a1a',
        'tertiary-container': '#007d55',
        'on-tertiary-container': '#bdffdb',
        'primary-fixed': '#dbe1ff',
        'on-secondary-container': '#fffbff',
        'surface-variant': '#e0e3e5',
        'error-container': '#ffdad6',
        'primary-container': '#2563eb',
        'tertiary-fixed-dim': '#4edea3',
        'surface-bright': '#f7f9fb',
        'surface-dim': '#d8dadc',
        'outline-variant': '#c3c6d7',
        'inverse-surface': '#2d3133',
        'on-surface': '#191c1e',
        'on-error-container': '#93000a',
        'on-tertiary': '#ffffff',
        'tertiary-fixed': '#6ffbbe',
        'inverse-primary': '#b4c5ff',
        'on-primary-fixed': '#00174b',
        'on-primary-fixed-variant': '#003ea8',
        'surface-container-lowest': '#ffffff',
        background: '#f7f9fb',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#b4c5ff',
        'on-primary': '#ffffff',
        'secondary-container': '#8a4cfc',
        tertiary: '#006242',
        'on-surface-variant': '#434655',
        'secondary-fixed': '#eaddff',
        outline: '#737686',
        'surface-container-highest': '#e0e3e5',
        'on-background': '#191c1e',
        primary: '#004ac6',
        'surface-tint': '#0053db',
        'on-tertiary-fixed': '#002113',
        'surface-container-low': '#f2f4f6',
        'surface-container-high': '#e6e8ea',
        'on-tertiary-fixed-variant': '#005236',
        secondary: '#712ae2',
      },
      fontFamily: {
        headline: ['Manrope', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      boxShadow: {
        card: '0 12px 40px rgba(25,28,30,0.06)',
        'card-hover': '0 12px 40px rgba(25,28,30,0.08)',
      },
      animation: {
        'float': 'float 15s infinite ease-in-out',
        'slide-in': 'slideIn 0.3s ease-out',
        'fade-in': 'fadeIn 0.2s ease-out',
      },
      keyframes: {
        float: {
          '0%': { transform: 'translateY(0px) translateX(0px)', opacity: '0.3' },
          '50%': { transform: 'translateY(-20px) translateX(10px)', opacity: '0.6' },
          '100%': { transform: 'translateY(0px) translateX(0px)', opacity: '0.3' },
        },
        slideIn: {
          '0%': { transform: 'translateX(100%)' },
          '100%': { transform: 'translateX(0)' },
        },
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
      },
    },
  },
  plugins: [],
};

export default config;
